from .base import BaseRepository
from .cart_item_repository import CartItemRepository
from .cart_repository import CartRepository
from .category_repository import CategoryRepository
from .order_item_repository = OrderItemRepository
from .order_repository = OrderRepository
from .payment_repository = PaymentRepository
from .product_repository = ProductRepository
from .role_repository = RoleRepository
from .shipping_repository = ShippingRepository
from .tag_repository = TagRepository
from .user_repository = UserRepository