from .base import BaseRepository
from .cart_item_repository import CartItemRepository
from .cart_repository = CartRepository
from .category_repository = CategoryRepository
from .course_enrollment_repository = CourseEnrollmentRepository
from .course_instructor_repository = CourseInstructorRepository
from .course_lesson_repository = CourseLessonRepository
from .course_module_repository = CourseModuleRepository
from .course_repository = CourseRepository
from .order_item_repository = OrderItemRepository
from .order_repository = OrderRepository
from .payment_repository = PaymentRepository
from .product_repository = ProductRepository
from .role_repository = RoleRepository
from .shipping_repository = ShippingRepository
from .tag_repository = TagRepository
from .training_category_repository = TrainingCategoryRepository
from .user_repository = UserRepository