"""Add role_id to users, remove user_role table

Revision ID: 1c48ebc7b92f
Revises: 04e3dbb368d6
Create Date: 2026-07-23 02:15:54.884400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c48ebc7b92f'
down_revision: Union[str, None] = '04e3dbb368d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    # Use batch mode for SQLite to add column and foreign key
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.CHAR(length=32), nullable=True))
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('role_id')
    op.create_table('user_role',
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('role_id', sa.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###
